### ISSUE TITLE
case study: zOS_tO60VMg v. ZNn2bpiJXNU

### ISSUE THREAD

**Issue by myf** [MilliVolt/matcher#28]
they are essentially the same video [one](https://www.youtube.com/watch?v=zOS_tO60VMg) and [two](https://www.youtube.com/watch?v=ZNn2bpiJXNU) that was published by different people under different names

the result is alarming

> python matcher.py ../streamer/buf/audio_zOS_tO60VMg.tmp ../streamer/buf/audio_ZNn2bpiJXNU.tmp
> OrderedDict([('scaled_score', 0.5015290519877675), ('score', 164), ('offset', 0), ('delay', 0.013333000000000039), ('master_seek', 1.6177550000000001), ('candidate_seek', 1.604422)])

they should have gotten a score very close to 1 instead of 0.5. 

the audio output of the two are different, with slight variance with each other, but still matches pretty darn well. baffled \

**Comment by vr2262** [comment]
Solution: madmom/SuperFlux

**Comment by myf** [comment]
solution: aubioonset
