### ISSUE TITLE
Triangular matrix for a2a matching

### ISSUE THREAD

**Issue by vr2262** [MilliVolt/matcher#31]
At the moment, we match every video to every other video (full matrix minus the diagonal, n^2 - n).

As @myf pointed out, `match(video_1, video_2)` should be exactly the same as `match(video_2, video_1)` (symmetric matrix), so we should calculate a triangular matrix minus the diagonal ((n^2)/2 - n). This requires two changes:
1. Change the unmatched query from `from_id != to_id` to `from_id < to_id`.
2. Make the application aware that the matrix is symmetric. Options:
   1. Insert two rows when calculating each match: (1,2) and (2,1)
   2. Make the application aware that if (2, 1) is missing, it should look for (1, 2)
   3. Redesign so that there is no order between 1 and 2.

**Comment by myf** [comment]
+1

**Comment by vr2262** [comment]
Actually this is all wrong (with the current implementation).

(1, 2) is different from (2, 1) if 1 and 2 have different durations.
